
services:
  postgres:
    image: postgres:15
    container_name: piscineds
    environment:
      - POSTGRES_USER=mdesmart
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  postgres_data:

# docker-compose up -d
# docker exec -it piscineds psql -U mdesmart -d piscineds
# SELECT current_user;
# SELECT current_database();