
services:
  postgres:
    image: postgres:15
    container_name: piscineds-ex01
    environment:
      - POSTGRES_USER=mdesmart
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

# docker-compose up -d
# docker exec -it piscineds psql -U mdesmart -d piscineds
# SELECT current_user;
# SELECT current_database();